// Generated by LiveScript 1.2.0
var fs, src, data, i$, len$, s, lines, obj, desc, j$, len1$, line, that;
fs = require('fs');
src = [['art.xml', '藝文'], ['economics.xml', '經濟'], ['envir.xml', '環境'], ['justice.xml', '司法'], ['local.xml', '地方'], ['media.xml', '媒體'], ['tech.xml', '科技'], ['china.xml', '中國'], ['entertain.xml', '娛樂'], ['global.xml', '國際'], ['life.xml', '生活'], ['main.xml', '要聞'], ['politics.xml', '政治']];
data = [];
for (i$ = 0, len$ = src.length; i$ < len$; ++i$) {
  s = src[i$];
  lines = fs.readFileSync("data/" + s[0]).toString().split('\n');
  obj = {};
  desc = "";
  for (j$ = 0, len1$ = lines.length; j$ < len1$; ++j$) {
    line = lines[j$];
    if (that = /<title>([^\]]+)<\/title>/.exec(line)) {
      obj.title = that[1];
    }
    if (that = /<link>([^\]]+)<\/link>/.exec(line)) {
      obj.link = that[1];
    }
    if (that = /<pubDate>(.+)<\/pubDate>/.exec(line)) {
      obj.date = that[1];
    }
    if (obj.title && obj.link && obj.date) {
      obj.cat = s[1];
      data.push(obj);
      desc = "";
      obj = {};
    }
  }
}
fs.writeFileSync('news.json', JSON.stringify(data));