// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('yslin', []);
x$.directive('lzload', function(){
  return {
    restrict: 'A',
    link: function(scope, e, attrs, ctrl){
      var des;
      des = $(e[0].parentNode.parentNode.parentNode);
      des.addClass('lz-hide');
      if (e.prop('tagName') === 'IMG') {
        return e.load(function(){
          des.addClass('lz-show');
          return scope.isotope.appended(des[0]);
        });
      } else {
        return scope.isotope.appended(e[0].parentNode.parentNode.parentNode);
      }
    }
  };
});
x$.factory('scrollr', function(){
  return {
    list: [],
    range: [],
    rlen: 0,
    register: function(t, s, e, cb){
      return this.list.push([t, s, e, cb]);
    },
    refresh: function(){
      var i$, ref$, len$, i, d, s, e;
      for (i$ = 0, len$ = (ref$ = this.list).length; i$ < len$; ++i$) {
        i = i$;
        d = ref$[i$];
        console.log(d, i);
        s = $(d[1]).offset().top;
        e = d[1] === d[2]
          ? $(d[2]).offset().top + $(d[2]).height()
          : d[2]
            ? $(d[2]).offset().top
            : $(d[1]).offset().top + 200;
        this.range[i] = [s, e, e - s];
      }
      this.range.sort(function(a, b){
        return b[0] - a[0];
      });
      return this.rlen = this.range.length;
    },
    tick: function(c){
      var w, i$, ref$, len$, i, item, ratio, ref1$, ref2$, results$ = [];
      w = $(window).height();
      for (i$ = 0, len$ = (ref$ = this.range).length; i$ < len$; ++i$) {
        i = i$;
        item = ref$[i$];
        ratio = (ref1$ = (ref2$ = parseInt(1000 * (c + w - item[0]) / item[2]) / 10) > 0 ? ref2$ : 0) < 100 ? ref1$ : 100;
        console.log(ratio);
        results$.push(this.list[i][3](ratio));
      }
      return results$;
    }
  };
});
x$.controller('main', function($scope, $interval, $timeout, scrollr){
  return $timeout(function(){
    scrollr.refresh();
    /*$interval ->
      console.log ">>>",$(window).scrollTop!
      scrollr.tick $(window).scrollTop!
    ,1000*/
    return $(window).scroll(function(){
      return scrollr.tick($(window).scrollTop());
    });
  }, 2000);
});