// Generated by LiveScript 1.2.0
var main;
main = function($scope){
  return setTimeout(function(){
    return skrollr.init({
      forceHeight: false,
      smoothScrolling: false
    });
  }, 1000);
};