// Generated by LiveScript 1.2.0
var navbar;
navbar = function($scope){
  $scope.showicon = 0;
  $scope.iconToggle = function(v){
    return $scope.showicon = v;
  };
  return $(window).scroll(function(){
    var t, nav;
    t = $(window).scrollTop();
    nav = [['#chapter-young', 1], ['#chapter-life', 2], ['#chapter-cmp', 3], ['#chapter-white', 4]].filter(function(it){
      var x, y;
      x = $(it[0]).offset().top;
      y = $(it[0]).height();
      if (t >= x && t <= x + y) {
        return true;
      } else {
        return false;
      }
    });
    if (nav.length) {
      if ($scope.navToggle !== nav[0][1]) {
        return $scope.$apply(function(){
          return $scope.navToggle = nav[0][1];
        });
      }
    }
  });
};