// Generated by LiveScript 1.2.0
var main;
main = function($scope){
  var h, dates, svg, x$, y$;
  h = $(window).height();
  dates = ['1954.04.17', '1980.02.28', '1981.07.03', '2014.02.03', '2014.05.14'];
  svg = d3.select('#timeline');
  x$ = svg.selectAll('g.point').data(dates);
  y$ = x$.enter().append('g').attr('class', 'point');
  y$.each(function(d, i){
    var it;
    it = d3.select(this);
    it.attr("data-" + (i - 2) * h, "opacity: 0;@transform:translate(0,550)");
    it.attr("data-" + (i - 1) * h, "opacity: 1;@transform:translate(0,550)");
    it.attr("data-" + (i + 0) * h, "opacity: 1;@transform:translate(0,300)");
    it.attr("data-" + (i + 1) * h, "opacity: 1;@transform:translate(0,50)");
    return it.attr("data-" + (i + 2) * h, "opacity: 0;@transform:translate(0,50)");
  });
  y$.append('circle').attr({
    cx: '50',
    cy: 0,
    r: '7'
  });
  y$.append('text').text(function(it){
    return it;
  }).attr({
    x: 65,
    y: 5
  });
  return skrollr.init({
    forceHeight: false
  });
};