// Generated by LiveScript 1.2.0
var young;
young = function($scope, $timeout){
  $scope.tab = 1;
  $scope.tgltab = function(it){
    $scope.tab = it;
    return setTimeout(function(){
      return $scope.skrollr.refresh();
    }, 1000);
  };
  $scope.tomenu = function(tab){
    $(document.body).animate({
      scrollTop: $(".avatar .ib.p1").offset().top - 100
    });
    $('#small-avatars').removeClass('active');
    return $scope.tgltab(tab);
  };
  $scope.sb = function(){
    return $(document.body).animate({
      scrollTop: 2500
    });
  };
  $scope.skrollr = skrollr.init({
    forceHeight: false,
    render: $scope.render
  });
  return $timeout(function(){
    return $scope.skrollr.refresh();
  }, 1000);
};