// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('yslin');
x$.controller('young', function($scope, $timeout, scrollr){
  $scope.scrollr = {
    rl: $('#young-sh .redline'),
    pk: $('#young-sh .speaker')
  };
  scrollr.register(function(){
    return $('#young-sh').offset().top + $(window).height() / 4;
  }, function(){
    return $(window).height() / 2;
  }, function(it){
    return $scope.scrollr.rl.each(function(i){
      return $(this).css({
        marginLeft: i
          ? it * 20 + "%"
          : (40 - it * 20) + "%"
      });
    });
  });
  scrollr.register(function(){
    return $('#young-sh').offset().top + $(window).height() / 4;
  }, function(){
    return $(window).height() / 2;
  }, function(it){
    return $scope.scrollr.pk.each(function(i){
      return $(this).css(i
        ? {
          marginLeft: (320 - it * 285) + "px",
          marginTop: (200 - it * 123) + "px"
        }
        : {
          marginLeft: (-410 + it * 285) + "px",
          marginTop: (200 - it * 123) + "px"
        });
    });
  });
  $scope.tab = 1;
  $scope.tgltab = function(it){
    return $scope.tab = it;
  };
  $scope.tomenu = function(tab){
    $(document.body).animate({
      scrollTop: $(".avatar .ib.p1").offset().top - 100
    });
    $('#small-avatars').removeClass('active');
    return $scope.tgltab(tab);
  };
  $scope.sb = function(){
    return $(document.body).animate({
      scrollTop: 2500
    });
  };
  $scope.navToggle = null;
  return $scope.saToggle = false;
});