// Generated by LiveScript 1.2.0
var young;
young = function($scope){
  $scope.tab = 1;
  $scope.tgltab = function(it){
    return $scope.tab = it;
  };
  $scope.tocontent = function(){
    return $(document.body).animate({
      scrollTop: 3815
    });
  };
  $scope.tomenu = function(){
    return $(document.body).animate({
      scrollTop: 2815
    });
  };
  $scope.sb = function(){
    return $(document.body).animate({
      scrollTop: 2500
    });
  };
  return skrollr.init({
    forceHeight: false,
    render: $scope.render
  });
};