// Generated by LiveScript 1.2.0
var young;
young = function($scope){
  $scope.tab = 1;
  $scope.tgltab = function(it){
    return $scope.tab = it;
  };
  $scope.sb = function(){
    $(document.body).animate({
      scrollTop: 2500
    });
    return console.log('ok');
  };
  return skrollr.init({
    forceHeight: false,
    render: $scope.render
  });
};